---
settings:
  name: Amazon S3 storage
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Amazon S3 Storage-Dokumente
    url: "/index.html"
  - title: Versionshinweise
    url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Amazon S3 Buckets anzeigen
      url: "/task-viewing-amazon-s3.html"
  - title: Management von S3-Buckets
    entries:
    - title: S3-Buckets hinzufügen
      url: "/task-add-s3-bucket.html"
    - title: Ändern der S3-Bucket-Einstellungen
      url: "/task-change-s3-bucket-settings.html"
    - title: Nutzen Sie NetApp Datenservices mit S3 Buckets
      url: "/task-s3-enable-data-services.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
