---
sidebar: sidebar 
permalink: task-s3-enable-data-services.html 
keywords: s3 buckets, s3 storage, s3 working environment, amazon s3 buckets, amazon s3 working environment 
summary: Nach der Erkennung von S3 Buckets in BlueXP können Sie NetApp Datenservices für Backup, Tiering, Klassifizierung und Datensynchronisierung verwenden. 
---
= Nutzen Sie NetApp Datenservices mit S3 Buckets
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nach der Erkennung von S3 Buckets in BlueXP können Sie NetApp Datenservices für Backup, Tiering, Klassifizierung und Datensynchronisierung verwenden.

* Backup von Daten aus Ihren lokalen ONTAP- und Cloud Volumes ONTAP-Systemen in S3 Objekt-Storage; *Cloud-Backup*
+
Um zu beginnen, gehen Sie auf den Bildschirm und ziehen Sie eine lokale ONTAP oder Cloud Volumes ONTAP Arbeitsumgebung in Ihrer Amazon S3 Arbeitsumgebung.

+
https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-ontap-backup-to-cloud.html["Erfahren Sie mehr über die Sicherung von ONTAP Daten in Amazon S3 Storage"^].

* Tiering * für das Tiering inaktiver Daten von lokalen ONTAP-Clustern auf S3 Objekt-Storage
+
Um zu beginnen, gehen Sie auf den Bildschirm und ziehen Sie eine lokale ONTAP-Arbeitsumgebung in Ihrer Amazon S3-Arbeitsumgebung.

+
https://docs.netapp.com/us-en/cloud-manager-tiering/task-tiering-onprem-aws.html["Weitere Informationen zum Tiering von ONTAP Daten in Amazon S3 Storage"^].

* Verwenden Sie *Cloud Sync*, um Daten mit oder von S3 Buckets zu synchronisieren.
+
Um zu beginnen, gehen Sie auf den Bildschirm und ziehen Sie die Quelle Arbeitsumgebung auf die Ziel-Arbeitsumgebung. Ihre Amazon S3-Arbeitsumgebung kann als Quelle oder als Ziel dienen.

+
Sie können auch Ihre Amazon S3-Arbeitsumgebung auswählen und im Servicebereich auf *Daten synchronisieren* klicken, um Daten mit oder aus S3-Buckets zu synchronisieren.

+
https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["Erfahren Sie mehr über den Cloud Sync Service"^].

* Verwenden Sie *Cloud Data Sense*, um Ihre S3-Buckets nach persönlichen und sensiblen Daten zu scannen. Cloud Data Sense kann jeden Bucket des Kontos scannen, unabhängig davon, ob er für eine NetApp Lösung erstellt wurde.
+
Wählen Sie zunächst Ihre Amazon S3-Arbeitsumgebung aus, und wählen Sie im Bereich *Klassifizierung* des Servicebereichs die entsprechende Option aus, um das Scannen Ihrer S3-Buckets zu starten.

+
https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-s3.html["Erfahren Sie mehr über den Cloud Data Sense Service"^].


