---
sidebar: sidebar 
permalink: task-s3-enable-data-services.html 
keywords: s3 buckets, s3 storage, s3 working environment, amazon s3 buckets, amazon s3 working environment 
summary: Nach der Erkennung von S3 Buckets in BlueXP können Sie NetApp Datenservices für Backup, Tiering, Klassifizierung und Datensynchronisierung verwenden. 
---
= Nutzen Sie NetApp Datenservices mit S3 Buckets
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nach der Erkennung von S3 Buckets in BlueXP können Sie NetApp Datenservices für Backup, Tiering, Klassifizierung und Datensynchronisierung verwenden.

* BlueXP Backup und Recovery* ermöglichen Ihnen das Backup Ihrer Daten von Ihren lokalen ONTAP und Cloud Volumes ONTAP Systemen auf S3 Objekt-Storage.
+
Um zu beginnen, gehen Sie auf den Bildschirm und ziehen Sie eine lokale ONTAP oder Cloud Volumes ONTAP Arbeitsumgebung in Ihrer Amazon S3 Arbeitsumgebung.

+
https://["Erfahren Sie mehr über die Sicherung von ONTAP Daten in Amazon S3 Storage"^].

* Mit *BlueXP Tiering* verschieben Sie inaktive Daten von lokalen ONTAP-Clustern auf S3 Objekt-Storage.
+
Um zu beginnen, gehen Sie auf den Bildschirm und ziehen Sie eine lokale ONTAP-Arbeitsumgebung in Ihrer Amazon S3-Arbeitsumgebung.

+
https://["Weitere Informationen zum Tiering von ONTAP Daten in Amazon S3 Storage"^].

* Verwenden Sie *BlueXP Kopier- und Synchronisierungsfunktion* für die Datensynchronisierung mit oder von S3 Buckets.
+
Um zu beginnen, gehen Sie auf den Bildschirm und ziehen Sie die Quelle Arbeitsumgebung auf die Ziel-Arbeitsumgebung. Ihre Amazon S3-Arbeitsumgebung kann als Quelle oder als Ziel dienen.

+
Sie können auch Ihre Amazon S3-Arbeitsumgebung auswählen und im Servicebereich auf *Kopieren und Synchronisieren* klicken, um Daten mit oder aus S3-Buckets zu synchronisieren.

+
https://["Weitere Informationen zum BlueXP Kopier- und Synchronisierungsservice"^].

* Mit *BlueXP Klassifizierung* scannen Sie Ihre S3-Buckets nach persönlichen und sensiblen Daten. Die BlueXP Klassifizierung kann beliebige Buckets im Konto scannen, unabhängig davon, ob sie für eine NetApp Lösung erstellt wurden.
+
Wählen Sie zunächst Ihre Amazon S3-Arbeitsumgebung aus, und wählen Sie im Bereich *Klassifizierung* des Servicebereichs die entsprechende Option aus, um das Scannen Ihrer S3-Buckets zu starten.

+
https://["Erfahren Sie mehr über den BlueXP Klassifizierungsservice"^].


